package com.fluxtion.compiler.generation;

public interface RuntimeConstants {
    String FLUXTION_NO_COMPILE = "FLUXTION.NO_COMPILE";
    String GENERATION_CLASSPATH = "FLUXTION.GENERATION.CLASSPATH";
    String OUTPUT_DIRECTORY = "FLUXTION.OUTPUT.DIRECTORY";
    String RESOURCES_DIRECTORY = "FLUXTION.RESOURCES.DIRECTORY";
}
