/*
 * Copyright (C) 2018 V12 Technology Ltd.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the Server Side Public License, version 1,
 * as published by MongoDB, Inc.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * Server Side Public License for more details.
 *
 * You should have received a copy of the Server Side Public License
 * along with this program.  If not, see
 * <http://www.mongodb.com/licensing/server-side-public-license>.
 */
package com.fluxtion.ext.streaming.api.group;

import com.fluxtion.ext.streaming.api.WrappedCollection;
import com.fluxtion.ext.streaming.api.Wrapper;
import com.fluxtion.ext.streaming.api.stream.StreamOperator;
import java.util.Collection;
import java.util.Map;

/**
 * Runtime interface for GroupBy instances generated by SEP.
 *
 * @param <T> he target type of the group
 * @author greg
 */
public interface GroupBy<T> extends WrappedCollection<T, Collection<T>, GroupBy<T>> {

    <K> T value(K key);

    <V extends Wrapper<T>> Map<?, V> getMap();

    @Override
    default GroupBy<T> id(String id) {
        return StreamOperator.service().nodeId(this, id);
    }

    @Override
    default GroupBy<T> resetNotifier(Object resetNotifier) {
        return this;
    }

    /**
     * The last record that was updated as a wrapped node
     *
     * @return the wrapped node
     */
    T record();

    /**
     * The type of the wrapped node
     *
     * @return wrapped node class
     */
    Class<T> recordClass();
}
